-- ============================================================================
-- LearnAnything — Multi-Agent Pipeline: document_extracts, lesson content cols,
--                study_plans pipeline tracking
-- Run this in Supabase Dashboard > SQL Editor
-- ============================================================================

-- ── Document Extracts table ──────────────────────────────────────────────────
-- Stores AI-extracted text from PDFs so re-generations can skip extraction.

create table if not exists public.document_extracts (
  id             uuid primary key default gen_random_uuid(),
  document_id    uuid not null references public.documents(id) on delete cascade,
  user_id        uuid not null references auth.users(id) on delete cascade,
  extracted_text text not null,
  outline        jsonb not null default '{}'::jsonb,
  created_at     timestamptz default now() not null,
  constraint uq_document_extract unique (document_id)
);

create index if not exists idx_document_extracts_document_id
  on public.document_extracts (document_id);

alter table public.document_extracts enable row level security;

create policy "Users can view own extracts"
  on public.document_extracts for select
  using (auth.uid() = user_id);

create policy "Users can insert own extracts"
  on public.document_extracts for insert
  with check (auth.uid() = user_id);

create policy "Users can delete own extracts"
  on public.document_extracts for delete
  using (auth.uid() = user_id);

-- ── Lesson content columns ──────────────────────────────────────────────────
-- Each lesson now carries slideshow and story card content generated by the pipeline.

alter table public.lessons
  add column if not exists slideshow_cards jsonb not null default '[]'::jsonb;

alter table public.lessons
  add column if not exists story_cards jsonb not null default '[]'::jsonb;

-- ── Study plan pipeline tracking ────────────────────────────────────────────

alter table public.study_plans
  add column if not exists pipeline_step text default null;

alter table public.study_plans
  add column if not exists settings jsonb not null default '{}'::jsonb;

-- Widen the status check to allow the existing values
-- (the constraint name may vary; drop by table + type to be safe)
alter table public.study_plans
  drop constraint if exists study_plans_status_check;

alter table public.study_plans
  add constraint study_plans_status_check
  check (status in ('generating', 'ready', 'error'));

-- Make quizzes.document_id nullable so pipeline-generated quizzes don't need one
alter table public.quizzes
  alter column document_id drop not null;
